version: "3"

services:
  pg-elixir:
    image: postgres:14.2-alpine
    container_name: pg-elixir
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "elixir_cam_api_dev"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: